// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymhpygmcsizmqozxvidr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltaHB5Z21jc2l6bXFvenh2aWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMTQxODQsImV4cCI6MjA1MDY5MDE4NH0.qIKbeglNp8dtDzbXBYO1LGveV6BsVxmRwwSmpzySngg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);